const List<String> drumStyles = [
  "ROCK-Standard",
  "ROCK-Swing Rock",
  "ROCK-Power Beat",
  "ROCK-Smooth",
  "ROCK-Mega Drive",
  "ROCK-Hard Rock",
  "ROCK-Boogie",
  "CTRY-Walk Line",
  "CTRY-Blue Grass",
  "CTRY-Country",
  "CTRY-Waltz",
  "CTRY-Train",
  "CTRY-Ctry Rock",
  "CTRY-Slowly",
  "BLUES-Slow Blues",
  "BLUES-Chicago",
  "BLUES-R&B",
  "BLUES-Blues Rock",
  "BLUES-Road Train",
  "BLUES-Shuffle",
  "METAL-2X Bass",
  "METAL-Close Beat",
  "METAL-Heavy Bass",
  "METAL-Fast",
  "METAL-Holy Case",
  "METAL-Open Hat",
  "METAL-Epic",
  "FUNK-Bouns",
  "FUNK-East Coast",
  "FUNK-New Mann",
  "FUNK-R&B Funk",
  "FUNK-80 Funk",
  "FUNK-Soul",
  "FUNK-Uncle Jam",
  "JAZZ-Blues Jazz",
  "JAZZ-Classic 1",
  "JAZZ-Classic 2",
  "JAZZ-Easy Jazz",
  "JAZZ-Fast",
  "JAZZ-Walking",
  "JAZZ-Smooth",
  "BALD-Bluesy",
  "BALD-Grooves",
  "BALD-Bald Rock",
  "BALD-Slow Rock",
  "BALD-Tutorial",
  "BALD-R&B Bald",
  "BALD-Gospel",
  "POP-Beach Side",
  "POP-Big City",
  "POP-Funky Pop",
  "POP-Modern",
  "POP-School Pop",
  "POP-Motown",
  "POP-Resistor",
  "REGGAE-Sherriff",
  "REGGAE-Santeria",
  "REGGAE-Reggae 3",
  "REGGAE-Reggae 4",
  "REGGAE-Reggae 5",
  "REGGAE-Reggae 6",
  "REGGAE-Reggae 7",
  "ELEC-Elec 1",
  "ELEC-Elec 2",
  "ELEC-Elec 3",
  "ELEC-ELEC-EDM",
  "ELEC-ELEC-TECH",
];